function [car, metric] = init()
%%%%%%%%%%%%%%%%%%CBF para
car.cars = 0; 
car.cars1 = 0; 
car.cars2 = 0; 
car.Car_leaves = 0; 
car.Car_leavesMain = 0; 
car.Car_leavesMerg = 0;
car.que1 = [];
car.que2 = [];
car.table = [];
metric.Ave_time = 0; 
metric.Ave_u2 = 0; 
metric.Ave_eng = 0; 
metric.Ave_u2Main = 0;
metric.Ave_u2Merg = 0; 
metric.Ave_engMain = 0; 
metric.Ave_engMerg = 0; 
metric.Ave_timeMain = 0; 
metric.Ave_timeMerg = 0; 
